-- MySQL Script generated by MySQL Workbench
-- 12/17/17 16:25:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema studies_finder
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema studies_finder
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `studies_finder` DEFAULT CHARACTER SET utf8 ;
USE `studies_finder` ;

-- -----------------------------------------------------
-- Table `studies_finder`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studies_finder`.`Pessoa` (
  `matricula` INT NOT NULL,
  `nome_pessoa` VARCHAR(45) NULL,
  `curso` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studies_finder`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studies_finder`.`Disciplina` (
  `codigo_disciplina` INT NOT NULL,
  `nokme_disciplina` VARCHAR(45) NULL,
  `Departamento_codigo_departamento` INT NOT NULL,
  PRIMARY KEY (`codigo_disciplina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studies_finder`.`Assunto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studies_finder`.`Assunto` (
  `codigo_assunto` INT NOT NULL,
  `nome_assunto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_assunto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studies_finder`.`Chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studies_finder`.`Chat` (
  `id_chat` INT NOT NULL,
  `nome_chat` VARCHAR(45) NULL,
  PRIMARY KEY (`id_chat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studies_finder`.`Possui`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studies_finder`.`Possui` (
  `Disciplina_codigo_disciplina` INT NOT NULL,
  `Assunto_codigo_assunto` INT NOT NULL,
  PRIMARY KEY (`Disciplina_codigo_disciplina`, `Assunto_codigo_assunto`),
  INDEX `fk_Disciplina_has_Assunto_Assunto1_idx` (`Assunto_codigo_assunto` ASC),
  INDEX `fk_Disciplina_has_Assunto_Disciplina1_idx` (`Disciplina_codigo_disciplina` ASC),
  CONSTRAINT `fk_Disciplina_has_Assunto_Disciplina1`
    FOREIGN KEY (`Disciplina_codigo_disciplina`)
    REFERENCES `studies_finder`.`Disciplina` (`codigo_disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Disciplina_has_Assunto_Assunto1`
    FOREIGN KEY (`Assunto_codigo_assunto`)
    REFERENCES `studies_finder`.`Assunto` (`codigo_assunto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studies_finder`.`Tem_interesse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studies_finder`.`Tem_interesse` (
  `Pessoa_matricula` INT NOT NULL,
  `Assunto_codigo_assunto` INT NOT NULL,
  PRIMARY KEY (`Pessoa_matricula`, `Assunto_codigo_assunto`),
  INDEX `fk_Pessoa_has_Assunto_Assunto1_idx` (`Assunto_codigo_assunto` ASC),
  INDEX `fk_Pessoa_has_Assunto_Pessoa1_idx` (`Pessoa_matricula` ASC),
  CONSTRAINT `fk_Pessoa_has_Assunto_Pessoa1`
    FOREIGN KEY (`Pessoa_matricula`)
    REFERENCES `studies_finder`.`Pessoa` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_has_Assunto_Assunto1`
    FOREIGN KEY (`Assunto_codigo_assunto`)
    REFERENCES `studies_finder`.`Assunto` (`codigo_assunto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studies_finder`.`Participa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studies_finder`.`Participa` (
  `Pessoa_matricula` INT NOT NULL,
  `Chat_id_chat` INT NOT NULL,
  PRIMARY KEY (`Pessoa_matricula`, `Chat_id_chat`),
  INDEX `fk_Pessoa_has_Chat_Chat1_idx` (`Chat_id_chat` ASC),
  INDEX `fk_Pessoa_has_Chat_Pessoa1_idx` (`Pessoa_matricula` ASC),
  CONSTRAINT `fk_Pessoa_has_Chat_Pessoa1`
    FOREIGN KEY (`Pessoa_matricula`)
    REFERENCES `studies_finder`.`Pessoa` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_has_Chat_Chat1`
    FOREIGN KEY (`Chat_id_chat`)
    REFERENCES `studies_finder`.`Chat` (`id_chat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studies_finder`.`Mensagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studies_finder`.`Mensagem` (
  `id_mensagem` INT NOT NULL,
  `mensagem` VARCHAR(200) NULL,
  `Chat_id_chat` INT NOT NULL,
  `Pessoa_matricula` INT NOT NULL,
  PRIMARY KEY (`id_mensagem`),
  INDEX `fk_Mensagem_Chat1_idx` (`Chat_id_chat` ASC),
  INDEX `fk_Mensagem_Pessoa1_idx` (`Pessoa_matricula` ASC),
  CONSTRAINT `fk_Mensagem_Chat1`
    FOREIGN KEY (`Chat_id_chat`)
    REFERENCES `studies_finder`.`Chat` (`id_chat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mensagem_Pessoa1`
    FOREIGN KEY (`Pessoa_matricula`)
    REFERENCES `studies_finder`.`Pessoa` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
